# doc-warnings: true
# test-warnings: false
strictness: medium
pep8:
  full: true
  disable:
    - E1004
pylint:
  disable:
    - syntax-error  # f-strings
    - invalid-sequence-index  # type annotations
max-line-length: 120
uses:
  - django
  - celery
# autodetect: yes
requirements:
  - django/requirements.txt

ignore-patterns:
  - /migrations/
  - /watson/

python-targets:
  - 3
