language: python

sudo: required

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo pip install docker-compose
  - ./run prod dc pull

script:
  - ./run prod test
