language: python

sudo: required

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo pip install docker-compose
  - touch django/local.env
  - docker-compose build

script:
  - ./run test
