# overrides for development
version: '2.1'
services:
  express:
    image: universitas/webpack:${IMAGE_VERSION:-edge}
    command: expressdev
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./webpack:/app/
      - node_modules:/app/node_modules/
    environment:
      - HOST_NAME
      - PUBLIC_PATH=http://${HOST_NAME:-localhost}:3000/static/


  webpack:
    image: universitas/webpack:${IMAGE_VERSION:-edge}
    command: dev-server
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./webpack:/app/
      - webpack_build:/var/build/
      - node_modules:/app/node_modules/
    environment:
      - BUILD_DIR=/var/build/
      - PUBLIC_PATH=http://${HOST_NAME:-localhost}:3000/static/


  web:
    command: runserver
    ports:
      - "8000:8000"
  flower:
    extends: django
    command: flower
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - celery
      - celerybeat

volumes:
  # mount locally for vim code completion with ternjs
  node_modules:
    driver_opts:
      type: local
      device: ${PWD}/webpack/node_modules
      o: bind
