# overrides for production
version: "2.1"
services:
  webpack:
    environment:
      - SENTRY_URL=https://e613c71ec39d471da53588b6aefe6bc0@dev.universitas.no/3
  express:
    extends: webpack
    command: express

  web:
    command: "uwsgi"
    environment:
      - SENTRY_URL=https://aa9a7700e53248c596e37c38ab4676fb@dev.universitas.no/2
      - DEBUG=False

  certbot:
    image: certbot/certbot:latest
    command: certificates
    volumes:
      - certificates:/etc/letsencrypt/
      - letsencrypt_challenge:/srv/

  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - django_static:/var/static/
      - django_media:/var/media/
      - certificates:/var/certificates/
      - letsencrypt_challenge:/var/letsencrypt/
    ports:
      - "${NGINX_PORT:-80}:80"
      - "443:443"

volumes:
  letsencrypt_challenge: {}
  certificates:
    driver_opts:
      type: local
      device: ${PWD}/volumes/certificates/
      o: bind
