# overrides for production
version: '2.1'
services:
  webpack:
    command: "true"  # noop command
    volumes:
      - ./build:/var/build/

  nginx:
    ports:
      - "80:80"

  web:
    command: "uwsgi"
    environment:
      - DEBUG=False
    volumes:
      - ./build:/var/build/
      - /srv/STAGING:/var/staging/

  celery:
    volumes:
      - /srv/STAGING:/var/staging/
