# overrides for production
version: '2.1'
services:
  webpack:
    command: "true"  # noop command
    volumes:
      - ./build:/var/build/

  nginx:
    ports:
      - "${NGINX_PORT:-80}:80"

  web:
    command: "uwsgi"
    environment:
      - DEBUG=False
    volumes:
      - ./build:/var/build/
      - ../STAGING:/var/staging/
      - ./logs:/var/logs/

  celery:
    volumes:
      - ../STAGING:/var/staging/
