# overrides for production
version: '2.1'
services:
  webpack:
    command: "true"  # noop command
    volumes:
      - ./build:/var/build/

  nginx:
    ports:
      - "${NGINX_PORT:-80}:80"

  web:
    command: "uwsgi"
    volumes:
      - ./build:/var/build/
    environment:
      - DEBUG=False

volumes:
  # mount locally for access with rsync
  django_staging:
    driver_opts:
      type: local
      device: ${PWD}/../STAGING
      o: bind
