# overrides for production
version: '2.1'
services:

  express:
    image: universitas/webpack:${IMAGE_VERSION:-edge}
    command: express
    volumes:
      - ./webpack:/app/
    environment:
      - PUBLIC_PATH=/static/
         
  nginx:
    ports:
      - "${NGINX_PORT:-80}:80"

  web:
    command: "uwsgi"
    volumes:
      - ./build:/var/build/
    environment:
      - DEBUG=False

