# overrides for production
version: '2.1'
services:

  express:
    extends: webpack
    command: express
         
  web:
    command: "uwsgi"
    environment:
      - DEBUG=False

  certbot:
    image: certbot/certbot:latest
    command: certificates
    volumes: 
      - certificates:/etc/letsencrypt/
      - letsencrypt_challenge:/srv/

  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - django_static:/var/static/
      - django_media:/var/media/
      - certificates:/var/certificates/
      - letsencrypt_challenge:/var/letsencrypt/
    ports:
      - "${NGINX_PORT:-8080}:80"
      - "443:443"

volumes: 
  letsencrypt_challenge: {}
  certificates:
    driver_opts:
      type: local
      device: ${PWD}/volumes/certificates/
      o: bind
