# overrides for production
version: '2.1'
services:

  express:
    image: universitas/webpack:${IMAGE_VERSION:-edge}
    command: serve
    tty: true
    volumes:
      - ./webpack:/app/
      - node_modules:/app/node_modules/
         
  nginx:
    ports:
      - "${NGINX_PORT:-80}:80"

  web:
    command: "uwsgi"
    volumes:
      - ./build:/var/build/
    environment:
      - DEBUG=False


volumes:
  # mount locally for access with rsync
  django_staging:
    driver_opts:
      type: local
      device: ${PWD}/../STAGING
      o: bind
